import type { SkillDefinition } from './types.js';

export const SKILL_CATALOG_DEFINITIONS: SkillDefinition[] = [
  // ==========================================
  // NHÓM A: CORE SKILLS (5) — NỀN TẢNG MIỄN PHÍ
  // ==========================================
  {
    id: 'core.repo-recon',
    name: 'Repository Reconnaissance & Framework Inspector',
    version: '1.0.0',
    category: 'CORE',
    description: 'Trinh sát toàn diện cây thư mục, bỏ qua rác vendor, nhận diện framework (Next.js, Vite, Express, FastAPI...), port, entrypoint và quy mô mã nguồn.',
    businessValue: 'Cung cấp bức tranh toàn cảnh về công nghệ và quy mô phần mềm cho nhà quản lý không rành kỹ thuật.',
    targetUser: 'Non-Tech Founders, Product Managers, Tech Leads',
    requiredAgent: 'agent-repo-analyst',
    requiredMcpTools: ['codetrust_inspect_project'],
    requiredPermissions: ['READ', 'ANALYZE'],
    dependencies: [],
    inputSchemaDescription: '{ targetPath: string }',
    outputSchemaDescription: '{ projectInfo: ProjectInfo, sourceFiles: string[] }',
    failureCases: ['Đường dẫn không tồn tại', 'Thư mục rỗng', 'Không có quyền đọc file hệ thống'],
    securityRisks: ['Đọc file nhạy cảm nếu không lọc thư mục hệ thống'],
    costPerRunEst: '$0.00 (Chạy thuần Node.js tĩnh)',
    expectedTokenUsage: '0 tokens',
    priority: 'P0',
    pricingModel: 'FREE',
    enabledByDefault: true,
  },
  {
    id: 'core.static-sec-scan',
    name: 'Deterministic Static Security Scanner',
    version: '1.0.0',
    category: 'CORE',
    description: 'Quét phân tích tĩnh 100% tất định (Zero-Hallucination) phát hiện lộ secret keys (OpenAI, GitHub, AWS), SQLi, eval(), innerHTML thô và vô hiệu hóa TLS.',
    businessValue: 'Ngăn chặn 100% rủi ro mất cắp tài khoản, lộ dữ liệu khách hàng hoặc bị hack máy chủ do lỗi sơ đẳng của code sinh từ AI.',
    targetUser: 'Founders, Developers, Security Auditors',
    requiredAgent: 'agent-security-inspector',
    requiredMcpTools: ['codetrust_scan_security'],
    requiredPermissions: ['READ', 'ANALYZE'],
    dependencies: [{ skillId: 'core.repo-recon', version: '^1.0.0' }],
    inputSchemaDescription: '{ targetPath: string, sourceFiles: string[] }',
    outputSchemaDescription: '{ findings: SecurityFinding[] }',
    failureCases: ['File mã hóa nhị phân không đọc được dạng text'],
    securityRisks: ['Vô tình ghi log nguyên văn API Key chưa được mặt nạ hóa (masking)'],
    costPerRunEst: '$0.00 (Chạy 100% Regex AST cục bộ)',
    expectedTokenUsage: '0 tokens',
    priority: 'P0',
    pricingModel: 'FREE',
    enabledByDefault: true,
  },
  {
    id: 'core.biz-risk-translator',
    name: 'Executive Business Risk & Impact Translator',
    version: '1.0.0',
    category: 'CORE',
    description: 'Chuyển hóa các thuật ngữ lỗ hổng kỹ thuật phức tạp sang ngôn ngữ tác động kinh doanh (tiền bạc, uy tín, pháp lý) bằng tiếng Việt rõ ràng.',
    businessValue: 'Giúp người duyệt code đưa ra quyết định kinh doanh chuẩn xác mà không cần biết lập trình.',
    targetUser: 'Non-Tech Founders, Business Executives, Product Owners',
    requiredAgent: 'agent-semantic-logic',
    requiredMcpTools: [],
    requiredPermissions: ['ANALYZE', 'REPORT'],
    dependencies: [
      { skillId: 'core.repo-recon', version: '^1.0.0' },
      { skillId: 'core.static-sec-scan', version: '^1.0.0' },
    ],
    inputSchemaDescription: '{ projectInfo: ProjectInfo, findings: SecurityFinding[], sampleSnippets: Array<{file, content}> }',
    outputSchemaDescription: '{ executiveSummary: ExecutiveSummary }',
    failureCases: ['Mất kết nối DeepSeek API -> Tự động chuyển sang Heuristic Fallback Engine'],
    securityRisks: ['Gửi snippet chứa bí mật nhạy cảm lên AI nếu chưa qua bước mask secret'],
    costPerRunEst: '~$0.001 - $0.003 (DeepSeek Chat API)',
    expectedTokenUsage: '800 - 2,500 tokens',
    priority: 'P0',
    pricingModel: 'FREE',
    enabledByDefault: true,
  },
  {
    id: 'core.trust-scorecard',
    name: 'Transparent Trust Scorecard & Grading Engine',
    version: '1.0.0',
    category: 'CORE',
    description: 'Tính toán chỉ số tin cậy minh bạch (0-100) theo công thức trọng số: Bảo mật (40%), Logic (35%), Ổn định cấu trúc (25%) kèm xếp hạng chữ A+ đến F.',
    businessValue: 'Tiêu chuẩn hóa chất lượng phần mềm thành con số cụ thể, dễ so sánh giữa các phiên bản hoặc giữa các nhà thầu phần mềm.',
    targetUser: 'All Stakeholders',
    requiredAgent: 'agent-quality-uat',
    requiredMcpTools: [],
    requiredPermissions: ['ANALYZE', 'REPORT'],
    dependencies: [
      { skillId: 'core.static-sec-scan', version: '^1.0.0' },
      { skillId: 'core.repo-recon', version: '^1.0.0' },
    ],
    inputSchemaDescription: '{ findings: SecurityFinding[], projectInfo: ProjectInfo }',
    outputSchemaDescription: '{ scores: Scores }',
    failureCases: ['Không có dữ liệu dự án đầu vào'],
    securityRisks: ['Không có'],
    costPerRunEst: '$0.00',
    expectedTokenUsage: '0 tokens',
    priority: 'P0',
    pricingModel: 'FREE',
    enabledByDefault: true,
  },
  {
    id: 'core.interactive-uat',
    name: 'Interactive 3-Step Acceptance Checklist Generator',
    version: '1.0.0',
    category: 'CORE',
    description: 'Tạo kịch bản kiểm thử nghiệm thu người dùng (UAT) trực quan gồm 3-5 bước hành động thực tế có checkbox tương tác trên báo cáo HTML.',
    businessValue: 'Trao quyền cho người quản lý tự tay bấm thử và kiểm chứng ứng dụng trước khi chuyển tiền nghiệm thu.',
    targetUser: 'Non-Tech Founders, QA Testers, Project Managers',
    requiredAgent: 'agent-semantic-logic',
    requiredMcpTools: ['codetrust_generate_uat'],
    requiredPermissions: ['ANALYZE', 'REPORT'],
    dependencies: [
      { skillId: 'core.repo-recon', version: '^1.0.0' },
      { skillId: 'core.biz-risk-translator', version: '^1.0.0' },
    ],
    inputSchemaDescription: '{ projectInfo: ProjectInfo, findings: SecurityFinding[] }',
    outputSchemaDescription: '{ uatChecklist: UATStep[] }',
    failureCases: ['AI sinh bước kiểm thử không thực tế khi thông tin dự án quá sơ sài'],
    securityRisks: ['Không có'],
    costPerRunEst: '~$0.001 (DeepSeek API)',
    expectedTokenUsage: '500 - 1,200 tokens',
    priority: 'P0',
    pricingModel: 'FREE',
    enabledByDefault: true,
  },

  // ==========================================
  // NHÓM B: OPTIONAL SKILLS (7) — BẬT/TẮT TÙY CHỌN
  // ==========================================
  {
    id: 'opt.pr-diff-auditor',
    name: 'Git PR Diff & Incremental Code Auditor',
    version: '1.0.0',
    category: 'OPTIONAL',
    description: 'Chỉ thẩm định các dòng code mới hoặc bị thay đổi trong Git Pull Request / Commit Diff, giảm thiểu thời gian quét và chi phí token.',
    businessValue: 'Tích hợp tự động vào CI/CD GitHub Actions để chặn các commit nguy hiểm mà không làm chậm tốc độ release.',
    targetUser: 'DevOps Engineers, Tech Leads, Code Reviewers',
    requiredAgent: 'agent-orchestrator',
    requiredMcpTools: ['codetrust_scan_security'],
    requiredPermissions: ['READ', 'ANALYZE'],
    dependencies: [{ skillId: 'core.static-sec-scan', version: '^1.0.0' }],
    inputSchemaDescription: '{ baseBranch: string, headBranch: string, repoPath: string }',
    outputSchemaDescription: '{ modifiedFilesCount: number, incrementalFindings: SecurityFinding[] }',
    failureCases: ['Thư mục không phải Git repository', 'Merge conflict'],
    securityRisks: ['Không có'],
    costPerRunEst: '$0.00 - $0.001',
    expectedTokenUsage: '0 - 500 tokens',
    priority: 'P1',
    pricingModel: 'INCLUDED_IN_PRO',
    enabledByDefault: false,
  },
  {
    id: 'opt.dep-cve-hunter',
    name: 'Dependency Vulnerability & CVE Hunter',
    version: '1.0.0',
    category: 'OPTIONAL',
    description: 'Phân tích file lock (`pnpm-lock.yaml`, `package-lock.json`, `poetry.lock`) đối chiếu kho dữ liệu lỗ hổng bảo mật quốc gia (NVD / OSV / GitHub Advisory).',
    businessValue: 'Phát hiện các thư viện mã nguồn mở có chứa lỗ hổng RCE hoặc Denial of Service trước khi hacker khai thác.',
    targetUser: 'Security Engineers, Developers',
    requiredAgent: 'agent-security-inspector',
    requiredMcpTools: ['codetrust_scan_security'],
    requiredPermissions: ['READ', 'ANALYZE'],
    dependencies: [{ skillId: 'core.repo-recon', version: '^1.0.0' }],
    inputSchemaDescription: '{ targetPath: string, lockfileType?: string }',
    outputSchemaDescription: '{ vulnerableDeps: Array<{ package: string, installed: string, cveId: string, severity: string, fixVersion: string }> }',
    failureCases: ['Dự án không có lockfile', 'Mạng ngoại tuyến không tra cứu được database CVE'],
    securityRisks: ['Không có'],
    costPerRunEst: '$0.00',
    expectedTokenUsage: '0 tokens',
    priority: 'P1',
    pricingModel: 'INCLUDED_IN_PRO',
    enabledByDefault: false,
  },
  {
    id: 'opt.api-contract-validator',
    name: 'REST API & OpenAPI Contract Integrity Validator',
    version: '1.0.0',
    category: 'OPTIONAL',
    description: 'Quét cấu trúc endpoint API (Express/FastAPI), kiểm tra xác thực tham số đầu vào (Zod/Pydantic/Joi) và tính hợp lệ của tài liệu OpenAPI/Swagger.',
    businessValue: 'Đảm bảo Backend không bị crash khi client gửi sai kiểu dữ liệu và ngăn ngừa lỗi Mass Assignment.',
    targetUser: 'Backend Engineers, Frontend Integrators',
    requiredAgent: 'agent-repo-analyst',
    requiredMcpTools: ['codetrust_inspect_project'],
    requiredPermissions: ['READ', 'ANALYZE'],
    dependencies: [{ skillId: 'core.repo-recon', version: '^1.0.0' }],
    inputSchemaDescription: '{ targetPath: string, swaggerPath?: string }',
    outputSchemaDescription: '{ unvalidatedEndpoints: string[], schemaDiscrepancies: string[] }',
    failureCases: ['File swagger cấu hình sai chuẩn YAML/JSON'],
    securityRisks: ['Không có'],
    costPerRunEst: '$0.00',
    expectedTokenUsage: '0 tokens',
    priority: 'P1',
    pricingModel: 'INCLUDED_IN_PRO',
    enabledByDefault: false,
  },
  {
    id: 'opt.secret-rotation-advisor',
    name: 'Compromised Secret Rotation & Incident Remediation',
    version: '1.0.0',
    category: 'OPTIONAL',
    description: 'Tự động tạo quy trình hướng dẫn từng bước (Step-by-step Runbook) để thu hồi khóa API bị lộ trên Git và cấu hình lại Key Management Service.',
    businessValue: 'Giúp lập trình viên xử lý nhanh sự cố lộ khóa trong vòng 15 phút, tránh bị trừ tiền API ngoài ý muốn.',
    targetUser: 'Developers, Tech Leads',
    requiredAgent: 'agent-semantic-logic',
    requiredMcpTools: [],
    requiredPermissions: ['ANALYZE', 'REPORT'],
    dependencies: [{ skillId: 'core.static-sec-scan', version: '^1.0.0' }],
    inputSchemaDescription: '{ exposedKeyFindings: SecurityFinding[] }',
    outputSchemaDescription: '{ remediationRunbook: Array<{ provider: string, revokeUrl: string, rotationSteps: string[] }> }',
    failureCases: ['Nhận diện sai nhà cung cấp khóa API (Unknown vendor)'],
    securityRisks: ['Không có'],
    costPerRunEst: '~$0.001',
    expectedTokenUsage: '500 - 1,000 tokens',
    priority: 'P1',
    pricingModel: 'INCLUDED_IN_PRO',
    enabledByDefault: false,
  },
  {
    id: 'opt.code-maintainability-radar',
    name: 'Code Smell & Maintainability Index Radar',
    version: '1.0.0',
    category: 'OPTIONAL',
    description: 'Đo lường độ phức tạp chu trình (Cyclomatic Complexity), phát hiện tệp "God-Object" (>800 dòng code), hàm lồng sâu (>4 cấp) và mã trùng lặp.',
    businessValue: 'Ngăn chặn tình trạng codebase trở thành mớ hỗn độn (Spaghetti code) khiến chi phí phát triển tính năng mới tăng vọt.',
    targetUser: 'Tech Leads, Architects',
    requiredAgent: 'agent-repo-analyst',
    requiredMcpTools: ['codetrust_inspect_project'],
    requiredPermissions: ['READ', 'ANALYZE'],
    dependencies: [{ skillId: 'core.repo-recon', version: '^1.0.0' }],
    inputSchemaDescription: '{ targetPath: string, maxLocThreshold?: number }',
    outputSchemaDescription: '{ maintainabilityIndex: number, godFiles: string[], complexFunctions: string[] }',
    failureCases: ['Code minified / bundled không phân tách được hàm'],
    securityRisks: ['Không có'],
    costPerRunEst: '$0.00',
    expectedTokenUsage: '0 tokens',
    priority: 'P2',
    pricingModel: 'INCLUDED_IN_PRO',
    enabledByDefault: false,
  },
  {
    id: 'opt.env-config-auditor',
    name: 'Environment Configuration & Secret Drift Auditor',
    version: '1.0.0',
    category: 'OPTIONAL',
    description: 'So khớp các biến môi trường được dùng trong mã nguồn với `.env.example`, phát hiện biến thiếu, giá trị mặc định nguy hiểm hoặc file `.env` bị commit nhầm.',
    businessValue: 'Đảm bảo ứng dụng chạy thông suốt khi deploy lên môi trường Production mà không bị thiếu biến môi trường bí mật.',
    targetUser: 'DevOps, Developers',
    requiredAgent: 'agent-security-inspector',
    requiredMcpTools: ['codetrust_scan_security'],
    requiredPermissions: ['READ', 'ANALYZE'],
    dependencies: [{ skillId: 'core.repo-recon', version: '^1.0.0' }],
    inputSchemaDescription: '{ targetPath: string }',
    outputSchemaDescription: '{ missingEnvVars: string[], unencryptedSecretsInSample: string[] }',
    failureCases: ['Không có file .env.example'],
    securityRisks: ['Đọc nhầm nội dung bí mật thật trong `.env`'],
    costPerRunEst: '$0.00',
    expectedTokenUsage: '0 tokens',
    priority: 'P1',
    pricingModel: 'INCLUDED_IN_PRO',
    enabledByDefault: false,
  },
  {
    id: 'opt.test-coverage-gap-analyst',
    name: 'Automated Test Gap & Critical Flow Analyst',
    version: '1.0.0',
    category: 'OPTIONAL',
    description: 'Trinh sát các file kiểm thử (`tests/`, `__tests__/`, `*.spec.ts`), xác định các luồng nghiệp vụ quan trọng (Auth, Payment, Order) chưa có test case bảo vệ.',
    businessValue: 'Cung cấp cơ sở định lượng để biết phần mềm đã sẵn sàng bàn giao hay vẫn còn chứa đựng rủi ro lỗi tiềm tàng.',
    targetUser: 'QA Leads, Tech Leads',
    requiredAgent: 'agent-repo-analyst',
    requiredMcpTools: ['codetrust_inspect_project'],
    requiredPermissions: ['READ', 'ANALYZE'],
    dependencies: [{ skillId: 'core.repo-recon', version: '^1.0.0' }],
    inputSchemaDescription: '{ targetPath: string }',
    outputSchemaDescription: '{ hasTestFramework: boolean, testFilesCount: number, uncoveredCriticalRoutes: string[] }',
    failureCases: ['Test runner cấu hình bằng framework lạ không nhận diện được'],
    securityRisks: ['Không có'],
    costPerRunEst: '$0.00',
    expectedTokenUsage: '0 tokens',
    priority: 'P2',
    pricingModel: 'INCLUDED_IN_PRO',
    enabledByDefault: false,
  },

  // ==========================================
  // NHÓM C: PREMIUM SKILLS (8) — BÁN QUA SKILL STORE
  // ==========================================
  {
    id: 'prem.owasp-top10-certifier',
    name: 'OWASP Top 10 Enterprise Compliance Certifier',
    version: '1.0.0',
    category: 'PREMIUM',
    description: 'Kiểm toán toàn diện đối chiếu theo 10 hạng mục bảo mật ứng dụng web của tổ chức OWASP và cấp báo cáo chứng nhận tuân thủ.',
    businessValue: 'Cung cấp hồ sơ bảo mật đạt chuẩn để doanh nghiệp tham gia đấu thầu hoặc ký kết hợp đồng với các khách hàng doanh nghiệp lớn.',
    targetUser: 'Enterprise Founders, Chief Information Security Officers (CISO)',
    requiredAgent: 'agent-security-inspector',
    requiredMcpTools: ['codetrust_scan_security', 'codetrust_audit'],
    requiredPermissions: ['READ', 'ANALYZE', 'REPORT'],
    dependencies: [
      { skillId: 'core.static-sec-scan', version: '^1.0.0' },
      { skillId: 'core.trust-scorecard', version: '^1.0.0' },
    ],
    inputSchemaDescription: '{ targetPath: string, enterpriseName: string }',
    outputSchemaDescription: '{ owaspMatrix: Record<string, { passed: boolean, details: string[] }>, certificationStatus: "CERTIFIED" | "NON_COMPLIANT" }',
    failureCases: ['Phát hiện vi phạm nghiêm trọng mục Broken Access Control'],
    securityRisks: ['Không có'],
    costPerRunEst: '~$0.01 - $0.03',
    expectedTokenUsage: '3,000 - 8,000 tokens',
    priority: 'P1',
    pricingModel: 'SUBSCRIPTION',
    enabledByDefault: false,
  },
  {
    id: 'prem.soc2-iso27001-readiness',
    name: 'SOC 2 Type II & ISO 27001 Readiness Inspector',
    version: '1.0.0',
    category: 'PREMIUM',
    description: 'Rà soát cấu trúc mã nguồn và hạ tầng cấu hình để đánh giá mức độ sẵn sàng cho các cuộc kiểm toán bảo mật chuẩn SOC 2 và ISO 27001.',
    businessValue: 'Tiết kiệm hàng chục nghìn USD chi phí tư vấn an ninh mạng trước khi bước vào cuộc đánh giá chứng chỉ chính thức.',
    targetUser: 'FinTech, HealthTech Startups, Compliance Managers',
    requiredAgent: 'agent-orchestrator',
    requiredMcpTools: ['codetrust_audit'],
    requiredPermissions: ['READ', 'ANALYZE', 'REPORT'],
    dependencies: [
      { skillId: 'core.static-sec-scan', version: '^1.0.0' },
      { skillId: 'opt.env-config-auditor', version: '^1.0.0' },
    ],
    inputSchemaDescription: '{ targetPath: string, standard: "SOC2" | "ISO27001" }',
    outputSchemaDescription: '{ readinessScore: number, auditGaps: string[], actionPlan: string[] }',
    failureCases: ['Thiếu nhật ký kiểm toán (Audit Trail) trong hệ thống'],
    securityRisks: ['Không có'],
    costPerRunEst: '~$0.02',
    expectedTokenUsage: '4,000 - 10,000 tokens',
    priority: 'P2',
    pricingModel: 'SUBSCRIPTION',
    enabledByDefault: false,
  },
  {
    id: 'prem.auto-pr-patch-generator',
    name: 'Autonomous Security Fix & PR Patch Generator',
    version: '1.0.0',
    category: 'PREMIUM',
    description: 'Tự động tạo mã sửa lỗi bảo mật (Code Patch / Git Branch) và mở Pull Request sẵn sàng để merge khắc phục lỗ hổng ngay lập tức.',
    businessValue: 'Giảm thời gian khắc phục lỗ hổng (Mean Time to Remediate - MTTR) từ vài ngày xuống còn vài phút.',
    targetUser: 'Engineering Managers, Developers',
    requiredAgent: 'agent-orchestrator',
    requiredMcpTools: ['codetrust_scan_security'],
    requiredPermissions: ['READ', 'ANALYZE', 'EXECUTE'],
    dependencies: [
      { skillId: 'core.static-sec-scan', version: '^1.0.0' },
      { skillId: 'opt.pr-diff-auditor', version: '^1.0.0' },
    ],
    inputSchemaDescription: '{ findingId: string, filePath: string, targetBranch: string }',
    outputSchemaDescription: '{ patchDiff: string, prUrl?: string, verifiedBuild: boolean }',
    failureCases: ['Mã sau khi vá làm gãy unit test hiện có'],
    securityRisks: ['Tạo commit tự động có thể bị lợi dụng nếu không qua bước phê duyệt (Human-in-the-loop)'],
    costPerRunEst: '~$0.015',
    expectedTokenUsage: '2,500 - 6,000 tokens',
    priority: 'P1',
    pricingModel: 'USAGE_BASED',
    enabledByDefault: false,
  },
  {
    id: 'prem.playwright-visual-sandbox',
    name: 'Containerized Playwright Visual UI & Sandbox Verifier',
    version: '1.0.0',
    category: 'PREMIUM',
    description: 'Tự động build và khởi chạy ứng dụng trong Container cô lập, dùng Playwright để chụp ảnh màn hình và phát hiện lỗi render giao diện.',
    businessValue: 'Xác minh giao diện web thực sự hiển thị đúng với người dùng cuối, phát hiện màn hình trắng hoặc nút bấm bị gãy.',
    targetUser: 'Designers, Product Managers, Founders',
    requiredAgent: 'agent-quality-uat',
    requiredMcpTools: ['codetrust_inspect_project'],
    requiredPermissions: ['READ', 'EXECUTE', 'REPORT'],
    dependencies: [
      { skillId: 'core.repo-recon', version: '^1.0.0' },
      { skillId: 'core.interactive-uat', version: '^1.0.0' },
    ],
    inputSchemaDescription: '{ targetPath: string, port?: number, headless?: boolean }',
    outputSchemaDescription: '{ screenshotUrls: string[], consoleErrors: string[], visualStabilityScore: number }',
    failureCases: ['Dự án không build được hoặc port bị chiếm dụng'],
    securityRisks: ['Thực thi mã lạ trong môi trường host nếu không có sandbox Docker/MicroVM'],
    costPerRunEst: '~$0.05 (Compute Container + Headless Chrome)',
    expectedTokenUsage: '500 tokens',
    priority: 'P2',
    pricingModel: 'USAGE_BASED',
    enabledByDefault: false,
  },
  {
    id: 'prem.license-ip-compliance',
    name: 'Open Source License & IP Risk Auditor',
    version: '1.0.0',
    category: 'PREMIUM',
    description: 'Rà soát giấy phép của tất cả các thư viện mã nguồn mở (`package.json`, licenses), phát hiện giấy phép có tính lây nhiễm (GPL, AGPL) gây rủi ro lộ bí mật thương mại.',
    businessValue: 'Bảo vệ tài sản trí tuệ và quyền sở hữu mã nguồn của startup trước các vòng gọi vốn đầu tư (M&A Due Diligence).',
    targetUser: 'Startup Founders, Legal Counsels, Investors',
    requiredAgent: 'agent-repo-analyst',
    requiredMcpTools: ['codetrust_inspect_project'],
    requiredPermissions: ['READ', 'ANALYZE', 'REPORT'],
    dependencies: [{ skillId: 'core.repo-recon', version: '^1.0.0' }],
    inputSchemaDescription: '{ targetPath: string, proprietaryLicenseType?: string }',
    outputSchemaDescription: '{ licensesDetected: Record<string, number>, viralLicenseRisks: string[], legalRiskScore: number }',
    failureCases: ['Gói thư viện không khai báo thuộc tính license trong package.json'],
    securityRisks: ['Không có'],
    costPerRunEst: '$0.00 - $0.001',
    expectedTokenUsage: '0 - 500 tokens',
    priority: 'P1',
    pricingModel: 'SUBSCRIPTION',
    enabledByDefault: false,
  },
  {
    id: 'prem.db-migration-safety',
    name: 'Database Migration & Query Performance Auditor',
    version: '1.0.0',
    category: 'PREMIUM',
    description: 'Thẩm định các tệp di chuyển cơ sở dữ liệu (Prisma, TypeORM, Knex, Flyway), phát hiện câu lệnh DROP TABLE, khóa bảng độc quyền hoặc truy vấn N+1.',
    businessValue: 'Ngăn chặn sự cố sập cơ sở dữ liệu và gián đoạn dịch vụ (Downtime) khi cập nhật phiên bản mới trên máy chủ.',
    targetUser: 'Database Administrators, Backend Tech Leads',
    requiredAgent: 'agent-security-inspector',
    requiredMcpTools: ['codetrust_scan_security'],
    requiredPermissions: ['READ', 'ANALYZE'],
    dependencies: [{ skillId: 'core.repo-recon', version: '^1.0.0' }],
    inputSchemaDescription: '{ targetPath: string, migrationDir?: string }',
    outputSchemaDescription: '{ destructiveOperations: string[], missingIndexes: string[], riskLevel: "LOW" | "MEDIUM" | "HIGH" }',
    failureCases: ['Không tìm thấy thư mục migration'],
    securityRisks: ['Không có'],
    costPerRunEst: '$0.00',
    expectedTokenUsage: '0 tokens',
    priority: 'P2',
    pricingModel: 'SUBSCRIPTION',
    enabledByDefault: false,
  },
  {
    id: 'prem.cloud-finops-auditor',
    name: 'Cloud Infrastructure & AI Token FinOps Auditor',
    version: '1.0.0',
    category: 'PREMIUM',
    description: 'Phân tích file cấu hình đám mây (Docker, Terraform, AWS SAM, Vercel) và các lời gọi mô hình AI để dự báo chi phí vận hành hàng tháng.',
    businessValue: 'Giúp doanh nghiệp tối ưu hóa chi phí đám mây và ngăn ngừa việc tài khoản AI bị tính phí đột biến ngoài tầm kiểm soát.',
    targetUser: 'CTOs, Finance Managers, Cloud Architects',
    requiredAgent: 'agent-orchestrator',
    requiredMcpTools: ['codetrust_inspect_project'],
    requiredPermissions: ['READ', 'ANALYZE', 'REPORT'],
    dependencies: [{ skillId: 'core.repo-recon', version: '^1.0.0' }],
    inputSchemaDescription: '{ targetPath: string }',
    outputSchemaDescription: '{ monthlyEstimatedCloudCost: string, tokenOptimizationTips: string[], wasteScore: number }',
    failureCases: ['Dự án không có file cấu hình hạ tầng đám mây'],
    securityRisks: ['Không có'],
    costPerRunEst: '~$0.005',
    expectedTokenUsage: '1,500 - 3,000 tokens',
    priority: 'P2',
    pricingModel: 'SUBSCRIPTION',
    enabledByDefault: false,
  },
  {
    id: 'prem.executive-pdf-deck-generator',
    name: 'Executive Board Deck & PDF Audit Dossier Generator',
    version: '1.0.0',
    category: 'PREMIUM',
    description: 'Tự động tạo hồ sơ thẩm định chuyên nghiệp định dạng PDF và bộ slide thuyết trình dành cho Nhà sáng lập báo cáo Nhà đầu tư.',
    businessValue: 'Xây dựng lòng tin tuyệt đối với các nhà đầu tư mạo hiểm trong quá trình thẩm định kỹ thuật (Technical Due Diligence).',
    targetUser: 'Founders, Investment Analysts, Advisors',
    requiredAgent: 'agent-quality-uat',
    requiredMcpTools: ['codetrust_audit'],
    requiredPermissions: ['READ', 'ANALYZE', 'REPORT'],
    dependencies: [
      { skillId: 'core.trust-scorecard', version: '^1.0.0' },
      { skillId: 'core.biz-risk-translator', version: '^1.0.0' },
    ],
    inputSchemaDescription: '{ auditReportId: string, companyLogoUrl?: string }',
    outputSchemaDescription: '{ pdfDownloadUrl: string, deckPresentationUrl: string }',
    failureCases: ['Lỗi render PDF canvas'],
    securityRisks: ['Không có'],
    costPerRunEst: '~$0.01',
    expectedTokenUsage: '1,000 tokens',
    priority: 'P2',
    pricingModel: 'USAGE_BASED',
    enabledByDefault: false,
  },

  // ==========================================
  // NHÓM D: INTERNAL SKILLS (4) — HỆ THỐNG NỘI BỘ
  // ==========================================
  {
    id: 'int.agent-task-router',
    name: 'Supervisor Task Router & Conflict Resolver',
    version: '1.0.0',
    category: 'INTERNAL',
    description: 'Định tuyến nhiệm vụ giữa các Sub-Agents, phân tách nhiệm vụ song song, phát hiện sai lệch dữ liệu và dung hòa kết quả thẩm định cuối cùng.',
    businessValue: 'Đảm bảo hệ sinh thái Multi-Agent hoạt động nhịp nhàng, nhất quán và không bao giờ đưa ra kết luận mâu thuẫn.',
    targetUser: 'Core Multi-Agent Engine',
    requiredAgent: 'agent-orchestrator',
    requiredMcpTools: [],
    requiredPermissions: ['READ', 'ANALYZE', 'EXECUTE', 'REPORT'],
    dependencies: [],
    inputSchemaDescription: '{ tasks: AgentTask[] }',
    outputSchemaDescription: '{ resolvedPlan: AgentTask[], executionOrder: string[] }',
    failureCases: ['Deadlock giữa các tác tử'],
    securityRisks: ['Leo thang đặc quyền giữa các tác tử nếu không kiểm soát permission token'],
    costPerRunEst: '$0.00',
    expectedTokenUsage: '0 tokens',
    priority: 'P0',
    pricingModel: 'INTERNAL_ONLY',
    enabledByDefault: true,
  },
  {
    id: 'int.token-economics-guardian',
    name: 'Token Economics & KV Prompt Cache Optimizer',
    version: '1.0.0',
    category: 'INTERNAL',
    description: 'Giám sát chi phí gọi LLM thời gian thực, tự động cấu trúc prompt để tận dụng tối đa cơ chế KV Cache của DeepSeek (giảm tới 90% chi phí).',
    businessValue: 'Bảo vệ lợi nhuận biên của nền tảng SaaS bằng cách tối ưu hóa triệt để chi phí gọi mô hình AI.',
    targetUser: 'Core Platform Runtime',
    requiredAgent: 'agent-semantic-logic',
    requiredMcpTools: [],
    requiredPermissions: ['ANALYZE'],
    dependencies: [],
    inputSchemaDescription: '{ rawPrompt: string, systemPromptPrefix: string }',
    outputSchemaDescription: '{ optimizedPrompt: string, cacheHitEstimatePercentage: number }',
    failureCases: ['Prompt bị xáo trộn thứ tự ngữ cảnh'],
    securityRisks: ['Không có'],
    costPerRunEst: '$0.00',
    expectedTokenUsage: '0 tokens',
    priority: 'P0',
    pricingModel: 'INTERNAL_ONLY',
    enabledByDefault: true,
  },
  {
    id: 'int.sandbox-execution-guard',
    name: 'Zero-Trust Sandbox & Workspace Isolation Guard',
    version: '1.0.0',
    category: 'INTERNAL',
    description: 'Cưỡng chế màng ngăn Path Traversal, kiểm tra giới hạn tài nguyên CPU/RAM/Disk và dọn dẹp các thư mục tạm sau khi hoàn tất kiểm toán.',
    businessValue: 'Bảo vệ máy chủ không bao giờ bị tấn công ghi đè file hệ thống hoặc tràn bộ nhớ khi xử lý file tải lên từ người dùng lạ.',
    targetUser: 'Server Runtime Security Layer',
    requiredAgent: 'agent-orchestrator',
    requiredMcpTools: [],
    requiredPermissions: ['READ', 'EXECUTE'],
    dependencies: [],
    inputSchemaDescription: '{ workspacePath: string, operation: "CREATE" | "READ" | "DELETE" }',
    outputSchemaDescription: '{ isAllowed: boolean, violationReason?: string }',
    failureCases: ['Phát hiện đường dẫn chứa ".." hoặc null bytes'],
    securityRisks: ['Bypass kiểm tra đường dẫn symlink'],
    costPerRunEst: '$0.00',
    expectedTokenUsage: '0 tokens',
    priority: 'P0',
    pricingModel: 'INTERNAL_ONLY',
    enabledByDefault: true,
  },
  {
    id: 'int.context-memory-compactor',
    name: 'Context Compactor & AST Pruning Memory Manager',
    version: '1.0.0',
    category: 'INTERNAL',
    description: 'Rút gọn ngữ cảnh thông minh đối với các dự án lớn (>100.000 dòng code), chỉ giữ lại chữ ký hàm và các đoạn mã nghi vấn trước khi gửi tới LLM.',
    businessValue: 'Tránh lỗi vượt ngưỡng Context Window của mô hình AI và giữ tốc độ phản hồi luôn dưới 3 giây.',
    targetUser: 'Agent Semantic Pipeline',
    requiredAgent: 'agent-semantic-logic',
    requiredMcpTools: [],
    requiredPermissions: ['ANALYZE'],
    dependencies: [{ skillId: 'core.repo-recon', version: '^1.0.0' }],
    inputSchemaDescription: '{ sourceFiles: string[], maxContextChars: number }',
    outputSchemaDescription: '{ compactedSnippets: Array<{ file: string, snippet: string }> }',
    failureCases: ['Cắt nhầm ngữ cảnh hàm gây mất thông tin lỗi logic'],
    securityRisks: ['Không có'],
    costPerRunEst: '$0.00',
    expectedTokenUsage: '0 tokens',
    priority: 'P1',
    pricingModel: 'INTERNAL_ONLY',
    enabledByDefault: true,
  },
];
